### ISSUE TITLE
Clean Coordinates Transformations

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/oceanbench#16]
> TLDR: We need some functions that *clean* the coordinates to all datasets that we use. These will follow a standard that we agree on for the entire pipeline (unless stated otherwise).

---
## Motivation

Every dataset under the sun has it's own standards. We want to have a standard transformation function which will be sure to changes all incoming data to comply with our coordinate standards.

---
## Conventions

<details><summary>Latitude</summary>

This is straightforward. We need to ensure the coordinate variable name is good. We also need to set the attributes accordingly.

* `units` - `degrees_north`
* `bnds` - `[-90, 90]`
* variable_name - `lat`
* `long_name` - `latitude`
* `name` - `Latitude`

</details>

<details><summary>Longitude</summary>

This is also straightforward. We need to ensure the coordinate variable name is good. We also need to set the attributes accordingly.

* `units` - `degrees_east`
* `bnds` - `[-180, 180]`
* variable name - `lon`
* `long_name` - `longitude`
* `name` - `Longitude`

</details>

<details><summary>Time</summary>

This is a bit trickier. We need to be sure we *don't* decode the coordinates.

```python
ds = xr.open_dataset('\path\to\dataset', decode_times=False)
```

Then later, we can assign the coordinates to be `pd.to_datetime`

```python
ds = ds.assign_coords(time=lambda ds: pd.to_datetime(ds.time))
```

</details>

---
## TODO

* [x] Correct `lon` coordinate
* [x] Correct `lat` coordinate
* [x] Correct `time` coordinate
