### ISSUE TITLE
2D+T Fourier Transformations

### ISSUE THREAD

**Issue by jejjohnson** [jejjohnson/oceanbench#19]
> We want to Fourier Transformations for the the full field 2D spatial-temporal grid using the `xrft` package.

---
## Motivation

---
## Previous Examples

I have some examples for functions:

* [2D+T FFT](https://github.com/jejjohnson/ml4ssh/blob/main/inr4ssh/_src/metrics/psd.py)
* [Isotropic FFT](https://github.com/jejjohnson/ml4ssh/blob/main/inr4ssh/_src/metrics/psd.py#L81) 

---
## TODO List

* [x] Utils for Irregular Grids (ask @anastasiaGor)
* [x] Space-Time Fourier Transformation
* [x] Space-Time Inverse Fourier Transformation
* [x] Isotropic Fourier Transformation
